[2014-08-15 11:28:36.542] [INFO] log - server pid: 5028
[2014-08-15 11:28:36.589] [INFO] log - server pid: 4232
[2014-08-15 11:34:39.116] [INFO] log - server pid: 3764
[2014-08-15 11:34:39.124] [INFO] log - server pid: 4976
[2014-08-15 12:24:03.096] [INFO] log - server pid: 1796
[2014-08-15 12:24:03.133] [INFO] log - server pid: 3412
[2014-08-15 12:24:57.265] [INFO] log - server pid: 3180
[2014-08-15 12:24:57.268] [INFO] log - server pid: 5008
[2014-08-15 12:33:14.761] [INFO] log - server pid: 5772
[2014-08-15 12:33:14.812] [INFO] log - server pid: 5800
[2014-08-15 12:33:23.793] [INFO] log - server pid: 5892
[2014-08-15 12:33:37.382] [INFO] log - server pid: 6056
[2014-08-15 12:53:01.016] [INFO] log - server pid: 5456
[2014-08-15 12:53:01.031] [INFO] log - server pid: 4336
[2014-08-15 13:03:40.371] [INFO] log - server pid: 3936
[2014-08-15 13:03:40.384] [INFO] log - server pid: 4612
[2014-08-15 13:05:11.843] [ERROR] log - error in domain: { [ReferenceError: err is not defined]
  domain_thrown: true,
  domain: { members: [], _events: { error: [Function] } } }
ReferenceError: err is not defined
    at Object.<anonymous> (E:\wangjh\APP\incloud\app.js:38:27)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:315:13)
[2014-08-15 13:05:12.882] [INFO] log - server pid: 3876
[2014-08-15 13:05:13.091] [INFO] log - server pid: 5240
[2014-08-15 13:05:45.693] [INFO] log - server pid: 5528
[2014-08-15 13:05:45.867] [INFO] log - server pid: 4148
[2014-08-15 13:06:09.074] [ERROR] log - error in domain: { [ReferenceError: aa is not defined]
  domain_thrown: true,
  domain: { members: [], _events: { error: [Function] } } }
ReferenceError: aa is not defined
    at Cluster.domain.run.process.env.node_env (E:\wangjh\APP\incloud\app.js:7:54)
    at Cluster.EventEmitter.emit (events.js:98:17)
    at ChildProcess.<anonymous> (cluster.js:313:13)
    at ChildProcess.g (events.js:185:14)
    at ChildProcess.EventEmitter.emit (events.js:91:17)
    at Process._handle.onexit (child_process.js:674:10)
    at process.startup.processMakeCallback.process._makeCallback (node.js:238:20)
[2014-08-15 13:06:09.081] [ERROR] log - uncaughtException { [ReferenceError: aa is not defined]
  domain_thrown: true,
  domain: { members: [], _events: { error: [Function] } } }
ReferenceError: aa is not defined
    at Cluster.domain.run.process.env.node_env (E:\wangjh\APP\incloud\app.js:7:54)
    at Cluster.EventEmitter.emit (events.js:98:17)
    at ChildProcess.<anonymous> (cluster.js:313:13)
    at ChildProcess.g (events.js:185:14)
    at ChildProcess.EventEmitter.emit (events.js:91:17)
    at Process._handle.onexit (child_process.js:674:10)
    at process.startup.processMakeCallback.process._makeCallback (node.js:238:20)
[2014-08-15 13:08:03.033] [INFO] log - server pid: 5736
[2014-08-15 13:08:03.103] [INFO] log - server pid: 5560
[2014-08-15 13:09:07.755] [ERROR] log - worker 5560 died (1). restarting...
[2014-08-15 13:09:07.777] [ERROR] log - error in domain: { [ReferenceError: ss is not defined]
  domain_thrown: true,
  domain: { members: [], _events: { error: [Function] } } }
ReferenceError: ss is not defined
    at Cluster.domain.run.process.env.node_env (E:\wangjh\APP\incloud\app.js:10:3)
    at Cluster.EventEmitter.emit (events.js:98:17)
    at ChildProcess.<anonymous> (cluster.js:313:13)
    at ChildProcess.g (events.js:185:14)
    at ChildProcess.EventEmitter.emit (events.js:91:17)
    at Process._handle.onexit (child_process.js:674:10)
    at process.startup.processMakeCallback.process._makeCallback (node.js:238:20)
[2014-08-15 13:09:07.781] [ERROR] log - uncaughtException { [ReferenceError: ss is not defined]
  domain_thrown: true,
  domain: { members: [], _events: { error: [Function] } } }
ReferenceError: ss is not defined
    at Cluster.domain.run.process.env.node_env (E:\wangjh\APP\incloud\app.js:10:3)
    at Cluster.EventEmitter.emit (events.js:98:17)
    at ChildProcess.<anonymous> (cluster.js:313:13)
    at ChildProcess.g (events.js:185:14)
    at ChildProcess.EventEmitter.emit (events.js:91:17)
    at Process._handle.onexit (child_process.js:674:10)
    at process.startup.processMakeCallback.process._makeCallback (node.js:238:20)
[2014-08-15 13:09:08.531] [INFO] log - server pid: 5832
[2014-08-15 13:09:55.603] [INFO] log - server pid: 5608
[2014-08-15 13:09:55.742] [INFO] log - server pid: 5440
[2014-08-15 13:10:18.126] [ERROR] log - worker 5440 died (1). restarting...
[2014-08-15 13:10:18.907] [INFO] log - server pid: 5924
[2014-08-15 13:36:55.088] [INFO] log - server pid: 2268
[2014-08-15 13:36:55.158] [INFO] log - server pid: 1924
[2014-08-15 13:48:04.142] [INFO] log - server pid: 4392
[2014-08-15 13:48:04.151] [INFO] log - server pid: 4436
[2014-08-15 13:48:30.068] [INFO] log - server pid: 4188
[2014-08-15 13:48:30.261] [INFO] log - server pid: 1056
[2014-08-15 13:48:35.781] [INFO] log - server pid: 3212
[2014-08-15 13:48:36.224] [INFO] log - server pid: 5408
[2014-08-15 13:50:07.333] [INFO] log - server pid: 5436
[2014-08-15 13:50:07.491] [INFO] log - server pid: 4080
[2014-08-15 13:50:33.053] [INFO] log - server pid: 6024
[2014-08-15 13:50:33.371] [INFO] log - server pid: 3036
[2014-08-15 13:51:15.143] [INFO] log - server pid: 5544
[2014-08-15 13:51:15.178] [INFO] log - server pid: 4492
[2014-08-15 13:57:20.761] [ERROR] log - error in domain: { [ReferenceError: err is not defined]
  domain_thrown: true,
  domain: { members: [], _events: { error: [Function] } } }
ReferenceError: err is not defined
    at Object.<anonymous> (E:\wangjh\APP\incloud\app.js:37:27)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:315:13)
[2014-08-15 13:57:20.771] [ERROR] log - error in domain: { [ReferenceError: err is not defined]
  domain_thrown: true,
  domain: { members: [], _events: { error: [Function] } } }
ReferenceError: err is not defined
    at Object.<anonymous> (E:\wangjh\APP\incloud\app.js:37:27)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:315:13)
[2014-08-15 13:57:33.680] [INFO] log - server pid: 5952
[2014-08-15 13:57:33.941] [INFO] log - server pid: 5764
[2014-08-15 14:06:49.981] [ERROR] log - error in domain: { [ReferenceError: err is not defined]
  domain_thrown: true,
  domain: { members: [], _events: { error: [Function] } } }
ReferenceError: err is not defined
    at Object.<anonymous> (E:\wangjh\APP\incloud\app.js:37:27)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:315:13)
[2014-08-15 14:06:49.989] [ERROR] log - error in domain: { [ReferenceError: err is not defined]
  domain_thrown: true,
  domain: { members: [], _events: { error: [Function] } } }
ReferenceError: err is not defined
    at Object.<anonymous> (E:\wangjh\APP\incloud\app.js:37:27)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:315:13)
[2014-08-15 14:07:58.991] [ERROR] log - try [TypeError: Object #<Route> has no method 'route']
TypeError: Object #<Route> has no method 'route'
    at Object.<anonymous> (E:\wangjh\APP\incloud\routes\index.js:43:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at E:\wangjh\APP\incloud\app.js:30:10
    at Domain.bind.b (domain.js:201:18)
    at Domain.run (domain.js:141:23)
[2014-08-15 14:07:59.347] [ERROR] log - try [TypeError: Object #<Route> has no method 'route']
TypeError: Object #<Route> has no method 'route'
    at Object.<anonymous> (E:\wangjh\APP\incloud\routes\index.js:43:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at E:\wangjh\APP\incloud\app.js:30:10
    at Domain.bind.b (domain.js:201:18)
    at Domain.run (domain.js:141:23)
[2014-08-15 14:09:10.049] [ERROR] log - try [TypeError: Object #<Route> has no method 'route']
TypeError: Object #<Route> has no method 'route'
    at Object.<anonymous> (E:\wangjh\APP\incloud\routes\index.js:43:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at E:\wangjh\APP\incloud\app.js:30:10
    at Domain.bind.b (domain.js:201:18)
    at Domain.run (domain.js:141:23)
[2014-08-15 14:09:10.063] [ERROR] log - try [TypeError: Object #<Route> has no method 'route']
TypeError: Object #<Route> has no method 'route'
    at Object.<anonymous> (E:\wangjh\APP\incloud\routes\index.js:43:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at E:\wangjh\APP\incloud\app.js:30:10
    at Domain.bind.b (domain.js:201:18)
    at Domain.run (domain.js:141:23)
[2014-08-15 14:11:27.182] [INFO] log - server pid: 1264
[2014-08-15 14:11:27.198] [INFO] log - server pid: 4916
[2014-08-15 14:11:44.708] [INFO] log - server pid: 4456
[2014-08-15 14:11:45.050] [INFO] log - server pid: 4344
[2014-08-15 14:15:35.430] [INFO] log - server pid: 872
[2014-08-15 14:15:35.502] [INFO] log - server pid: 5500
[2014-08-15 14:24:43.408] [INFO] log - server pid: 4920
[2014-08-15 14:24:43.878] [INFO] log - server pid: 6080
[2014-08-15 14:25:05.152] [INFO] log - server pid: 4556
[2014-08-15 14:25:05.171] [INFO] log - server pid: 3576
[2014-08-15 14:27:48.614] [INFO] log - server pid: 5824
[2014-08-15 14:27:48.614] [INFO] log - server pid: 2912
[2014-08-15 14:29:39.701] [ERROR] log - { [HttpError: This ssh key is in use]
  _isError: true,
  name: 'HttpError',
  httpCode: 409,
  restCode: 'InvalidArgument',
  message: 'This ssh key is in use',
  details: 
   { expected: [ 200, 201 ],
     statusCode: 409,
     headers: 
      { connection: 'close',
        date: 'Fri, 15 Aug 2014 06:29:21 GMT',
        server: 'SmartDataCenter',
        'x-api-version': '6.5.0',
        'x-request-id': 'cbf70d36-9472-49c9-abbb-eef13df8718c',
        'x-response-time': '165',
        'content-length': '61',
        'content-md5': 'eAbWcyVyeku03FNeCAZcWQ==',
        'content-type': 'application/json',
        'access-control-allow-origin': '*',
        'access-control-allow-methods': 'OPTIONS, POST, POST, POST, POST, POST, GET, GET, GET, GET, GET',
        'access-control-allow-headers': 'Accept, Content-Type, Content-Length, Date, X-Api-Version',
        'access-control-expose-headers': 'X-Api-Version, X-Request-Id, X-Response-Time' },
     object: { code: 'InvalidArgument', message: 'This ssh key is in use' } } }
HttpError: This ssh key is in use
    at module.exports.newError (E:\wangjh\APP\incloud\node_modules\smartdc\node_modules\restify\lib\error.js:21:13)
    at RestClient.post (E:\wangjh\APP\incloud\node_modules\smartdc\node_modules\restify\lib\client.js:188:17)
    at IncomingMessage.endResponse (E:\wangjh\APP\incloud\node_modules\smartdc\node_modules\restify\lib\client.js:463:9)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1356:20)
    at CleartextStream.CryptoStream._push (tls.js:515:27)
    at SecurePair.cycle (tls.js:869:20)
    at EncryptedStream.CryptoStream.write (tls.js:256:13)
[2014-08-15 14:30:38.294] [ERROR] log - uncaughtException [ReferenceError: res is not defined]
ReferenceError: res is not defined
    at module.exports.passwordIO (E:\wangjh\APP\incloud\routes\account.js:154:5)
    at CAPI.updateAccount (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:652:12)
    at RestClient.put (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:163:12)
    at IncomingMessage.endResponse (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:463:9)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socketOnData [as ondata] (http.js:1356:20)
    at TCP.onread (net.js:404:27)
    at process.startup.processMakeCallback.process._makeCallback (node.js:238:20)
[2014-08-15 14:31:43.728] [INFO] log - server pid: 5420
[2014-08-15 14:31:43.920] [INFO] log - server pid: 5184
[2014-08-15 14:32:27.261] [INFO] log - server pid: 4848
[2014-08-15 14:32:27.729] [INFO] log - server pid: 3744
[2014-08-15 14:34:59.743] [INFO] log - server pid: 4168
[2014-08-15 14:35:00.099] [INFO] log - server pid: 5552
[2014-08-15 14:35:38.771] [ERROR] log - { [HttpError: Not Found]
  _isError: true,
  name: 'HttpError',
  httpCode: 404,
  restCode: 'ResourceNotFound',
  message: 'Not Found',
  cause: 
   { [HttpError: [object Object]]
     _isError: true,
     name: 'HttpError',
     httpCode: 404,
     restCode: 'ResourceNotFound',
     message: { errors: 'Not Found' },
     details: 
      { expected: [Object],
        statusCode: 404,
        headers: [Object],
        object: [Object] } } }
HttpError: Not Found
    at module.exports.newError (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\error.js:21:13)
    at CAPI._translateError (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:902:11)
    at CAPI.authenticate (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:209:35)
    at CAPI._getSalt (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:751:21)
    at RestClient.get (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:225:14)
    at IncomingMessage.endResponse (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:463:9)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socketOnData [as ondata] (http.js:1356:20)
[2014-08-15 14:35:43.388] [ERROR] log - { [HttpError: Not Found]
  _isError: true,
  name: 'HttpError',
  httpCode: 404,
  restCode: 'ResourceNotFound',
  message: 'Not Found',
  cause: 
   { [HttpError: [object Object]]
     _isError: true,
     name: 'HttpError',
     httpCode: 404,
     restCode: 'ResourceNotFound',
     message: { errors: 'Not Found' },
     details: 
      { expected: [Object],
        statusCode: 404,
        headers: [Object],
        object: [Object] } } }
HttpError: Not Found
    at module.exports.newError (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\error.js:21:13)
    at CAPI._translateError (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:902:11)
    at CAPI.authenticate (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:209:35)
    at CAPI._getSalt (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:751:21)
    at RestClient.get (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:225:14)
    at IncomingMessage.endResponse (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:463:9)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socketOnData [as ondata] (http.js:1356:20)
[2014-08-15 14:35:50.844] [ERROR] log - { [HttpError: Not Found]
  _isError: true,
  name: 'HttpError',
  httpCode: 404,
  restCode: 'ResourceNotFound',
  message: 'Not Found',
  cause: 
   { [HttpError: [object Object]]
     _isError: true,
     name: 'HttpError',
     httpCode: 404,
     restCode: 'ResourceNotFound',
     message: { errors: 'Not Found' },
     details: 
      { expected: [Object],
        statusCode: 404,
        headers: [Object],
        object: [Object] } } }
HttpError: Not Found
    at module.exports.newError (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\error.js:21:13)
    at CAPI._translateError (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:902:11)
    at CAPI.authenticate (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:209:35)
    at CAPI._getSalt (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:751:21)
    at RestClient.get (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:225:14)
    at IncomingMessage.endResponse (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:463:9)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socketOnData [as ondata] (http.js:1356:20)
[2014-08-15 14:35:56.619] [ERROR] log - { [HttpError: Not Found]
  _isError: true,
  name: 'HttpError',
  httpCode: 404,
  restCode: 'ResourceNotFound',
  message: 'Not Found',
  cause: 
   { [HttpError: [object Object]]
     _isError: true,
     name: 'HttpError',
     httpCode: 404,
     restCode: 'ResourceNotFound',
     message: { errors: 'Not Found' },
     details: 
      { expected: [Object],
        statusCode: 404,
        headers: [Object],
        object: [Object] } } }
HttpError: Not Found
    at module.exports.newError (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\error.js:21:13)
    at CAPI._translateError (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:902:11)
    at CAPI.authenticate (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:209:35)
    at CAPI._getSalt (E:\wangjh\APP\incloud\node_modules\sdc-clients\lib\capi.js:751:21)
    at RestClient.get (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:225:14)
    at IncomingMessage.endResponse (E:\wangjh\APP\incloud\node_modules\sdc-clients\node_modules\restify\lib\client.js:463:9)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socketOnData [as ondata] (http.js:1356:20)
[2014-08-15 14:40:38.417] [INFO] log - server pid: 5948
[2014-08-15 14:40:38.592] [INFO] log - server pid: 3528
[2014-08-15 14:42:07.539] [INFO] log - server pid: 4004
[2014-08-15 14:42:07.672] [INFO] log - server pid: 4488
[2014-08-15 14:42:17.694] [ERROR] log - { [Error: ENOENT, open 'E:\wangjh\APP\incloud\config\PASSWORD_RESET_EMAIL.html']
  errno: 34,
  code: 'ENOENT',
  path: 'E:\\wangjh\\APP\\incloud\\config\\PASSWORD_RESET_EMAIL.html' }
Error: ENOENT, open 'E:\wangjh\APP\incloud\config\PASSWORD_RESET_EMAIL.html'
[2014-08-15 14:44:18.258] [ERROR] log - { [Error: ENOENT, open 'E:\wangjh\APP\incloud\config\PASSWORD_RESET_EMAIL.html']
  errno: 34,
  code: 'ENOENT',
  path: 'E:\\wangjh\\APP\\incloud\\config\\PASSWORD_RESET_EMAIL.html' }
Error: ENOENT, open 'E:\wangjh\APP\incloud\config\PASSWORD_RESET_EMAIL.html'
